-- T0.3 foundation. UUID values are generated by the backend; no seed accounts or types.
CREATE TABLE users (
    id uuid PRIMARY KEY,
    username text NOT NULL,
    email text,
    display_name text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL,
    account_status text NOT NULL DEFAULT 'ACTIVE',
    auth_version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_username_nonblank CHECK (length(btrim(username)) > 0),
    CONSTRAINT ck_users_email_nonblank CHECK (email IS NULL OR length(btrim(email)) > 0),
    CONSTRAINT ck_users_display_name_nonblank CHECK (length(btrim(display_name)) > 0),
    CONSTRAINT ck_users_password_hash_nonblank CHECK (length(btrim(password_hash)) > 0),
    CONSTRAINT ck_users_role CHECK (role IN ('EMPLOYEE', 'SUPPORT_AGENT', 'ADMINISTRATOR')),
    CONSTRAINT ck_users_account_status CHECK (account_status IN ('ACTIVE', 'LOCKED')),
    CONSTRAINT ck_users_auth_version CHECK (auth_version >= 0)
);

CREATE UNIQUE INDEX ux_users_username_normalized ON users (lower(btrim(username)));
CREATE UNIQUE INDEX ux_users_email_normalized ON users (lower(btrim(email))) WHERE email IS NOT NULL;

CREATE TABLE request_types (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_request_types_name_nonblank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_request_types_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX ux_request_types_name_normalized ON request_types (lower(btrim(name)));
